{{- if .Values.secret.sealedSecrets.sealedSecretEnvs }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: {{ .Release.Name }}-secretenvs
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  encryptedData:
    {{- range $key, $val := .Values.secret.sealedSecrets.sealedSecretEnvs }}
    {{ $key }}: {{ $val }}
    {{- end }}
{{- end }}